---
experiments:
  metero_use: ['2m_temperature',
               'boundary_layer_height',  # Comment out for no_BPL experiments.
               'k_index',
               'relative_humidity+950',
               'surface_pressure',
               'total_precipitation',
               'u_component_of_wind+950',
               'v_component_of_wind+950',]

data:
  metero_var:
    ['100m_u_component_of_wind',
     '100m_v_component_of_wind',
     '2m_dewpoint_temperature',
     '2m_temperature',
     'boundary_layer_height',
     'k_index',
     'relative_humidity+950',
     'relative_humidity+975',
     'specific_humidity+950',
     'surface_pressure',
     'temperature+925',
     'temperature+950',
     'total_precipitation',
     'u_component_of_wind+950',
     'v_component_of_wind+950',
     'vertical_velocity+950',
     'vorticity+950']

dataset:
  data_start: [[2015, 1, 1, 0, 0], GMT]
  data_end: [[2018, 12, 31, 21, 0], GMT]

  2015:
    train_start: [[2015, 1, 1], GMT]
    train_end: [[2015, 8, 31], GMT]
    val_start: [[2015, 9, 1], GMT]
    val_end: [[2015, 10, 31], GMT]
    test_start: [[2015, 11, 1], GMT]
    test_end: [[2015, 12, 31], GMT]

  2016:
    train_start: [[2015, 1, 1], GMT]
    train_end: [[2015, 8, 31], GMT]
    val_start: [[2015, 9, 1], GMT]
    val_end: [[2015, 10, 31], GMT]
    test_start: [[2016, 11, 1], GMT]
    test_end: [[2016, 12, 31], GMT]

  2017:
    train_start: [[2015, 1, 1], GMT]
    train_end: [[2015, 8, 31], GMT]
    val_start: [[2015, 9, 1], GMT]
    val_end: [[2015, 10, 31], GMT]
    test_start: [[2017, 11, 1], GMT]
    test_end: [[2017, 12, 31], GMT]

  2018:
    train_start: [[2015, 1, 1], GMT]
    train_end: [[2015, 8, 31], GMT]
    val_start: [[2015, 9, 1], GMT]
    val_end: [[2015, 10, 31], GMT]
    test_start: [[2018, 11, 1], GMT]
    test_end: [[2018, 12, 31], GMT]
